### ISSUE TITLE
Just installed but it required and executed a downgrade of MPL

### ISSUE THREAD

**Issue by dartdog** [ayush1997/visualize_ML#1]
The PIP install downgraded MPL from 1.5.1 to 1.4.2 and also required the installation of "sudo apt-get install blt-dev" for freetype to build,, I had not previously run into that before? Any advice on how to preserve Matplotlib at 1.5.1 and of course MPL 2.0 is about to drop soon as well? The package looks quite useful with some nice ideas!

**Comment by ayush1997** [comment]
Hi @dartdog ,
Thanks for pointing out this issue !
I have made the required changes for downgrade issue in latest release 0.2.2 and also added  the command in install section(README.md) which will install all system dependencies required for matplotlib. Hope this helps.

Thanks

**Comment by dartdog** [comment]
Fantastic quick response, thanks will be trying out shortly, installed fine now on a new instance..
