### ISSUE TITLE
Can't get graphs to space right

### ISSUE THREAD

**Issue by dartdog** [ayush1997/visualize_ML#3]
Not sure what is going on tried looking at the code.. I'm using Jupyter notebook if that is messing stuff up?
data: 
state   region  age gender  race    marital_status  ptype   status-grp
0   IA  3   73  M   W   M   Patient NaN
1   IL  2   57  M   W   S   Patient NaN
2   WI  2   32  F   W   U   Patient NaN
3   WI  2   54  F   W   U   Patient NaN
4   IL  2   56  F   W   M   Patient NaN
5   WI  2   31  F   W   S   Patient 

input line:
explore.plot(df2,['state','region','age','gender','race','marital_status','ptype','status-grp'],PLOT_COLUMNS_SIZE=2,bin_size=20,
             bar_width=0.2,wspace=.75,hspace=.75)
result:
![vizml](https://cloud.githubusercontent.com/assets/87834/17860137/f0877c64-6851-11e6-99da-2fec1cf522a6.png)

**Comment by ayush1997** [comment]
Hi @dartdog 
Have you encoded the data i.e changed categorical character data to numerical (M->1,F-0 etc).Try setting PLOT_COLUMNS_SIZE to value greater than 2 like 3 or 4.I think the Jupyter notebook might be hindering, it would be great if you can provide me data you are using it on so that I can try it on my side.

Thanks!

**Comment by dartdog** [comment]
I removed the categorical data and am now getting marginally better results but still no effect with the white space parameters.. The column size does work but I reduced the data to only two variables But still no effect on the whitespace variables Eg I can't increase the space between the plots
So now I just use age and region, both of which are numeric.. (the 1st two numeric columns in the above data frame other than the data frame index. The full dataset is rather large..  So maybe it is a Jupyter thing, but I have been able to manipulate graphs in it otherwise.. Not sure if there would be an easy way to pass the whole plot object back so more could be done with it?

**Comment by ayush1997** [comment]
The jupyter in hindering the wspace variable, it would work well if you execute it otherwise as full screen matplotlib window is generated.
Can you elaborate more on the last question,like what else would you like to do with it?

**Comment by dartdog** [comment]
well it is possible to layout better in Jupyter but since I don't get the figure returned I can't do anything with it in Jupyter. Like fix the margins.. Or for that matter titles and or more stuff..?? Almost all our work for initial exploration is in Jupyter so It would be great to have this "play well" if possible.. I'm looking at how to handle categoricals in a systematic manner.. (a pain point) In particular to really be able to use the bivariate stuff you have. I make use of the pandas profiling package for some of our up front analysis  and hope to improve our up front analysis as we keep getting to the end of ML modeling only to find there was more we should have looked at up front, I think you have a good start for that!

**Comment by ayush1997** [comment]
So I have to look into it for adding support for jupyter. Thanks for pointing it.
Maybe issue#2 might help to handle text categorical variables.

**Comment by dartdog** [comment]
thanks! H Ave looked at the issue you mentioned,, I'm hoping to develop something a bit more automatic perhaps incorporating it (don't know how I'll do..) :-)
